{% set data= load_setup_py_data() %}
package:
  name: ts-fiberspectrograph
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
  - run_fiberspectrograph = lsst.ts.fiberspectrograph:run_fiberspectrograph
  string: "py{{ PY_VER | replace('.', '') }}{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"
  

test:
  requires:
    - ts-conda-build =0.5
    - ts-xml {{ xml_version }}
    - ts-salobj {{ salobj_version }}
  source_files:
    - bin
    - pyproject.toml
    - python
    - tests
  commands:
    - pytest

requirements:
  host:
    - pip
    - python {{ python }}
    - setuptools >={{setuptools}}
    - setuptools_scm ={{setuptools_scm}}
  run:
    - python {{ python }}
    - ts-xml
    - ts-salobj
    - libusb
