{% set data= load_setup_py_data() %}
package:
  name: ts-fiberspectrograph
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
  - run_fiberspectrograph = lsst.ts.fiberspectrograph:run_fiberspectrograph

test:
  requires:
    - ts-conda-build =0.4
    - ts-dds
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
  source_files:
    - bin
    - pyproject.toml
    - python
    - tests
  commands:
    - pytest

requirements:
  host:
    - pip
    - python {{ python }}
    - setuptools
    - setuptools_scm
  build:
    - python {{ python }}
    - setuptools
    - setuptools_scm
  run:
    - python {{ python }}
    - ts-idl
    - ts-salobj
